---
output: 
  html_document:
    code_folding: hide
---


```{r boilerplate}
library(tidyverse)
library(lubridate)
library(augsynth)
library(gsynth)
library(panelView)
library(tidycensus)
library(did)
data(fips_codes)
```


```{r read_data}

dat <- read_csv("../data/fertility_data.csv") %>%
  mutate(year_bm = year + (bmcode - 1) / 6,
         time = ymd(paste0(year, "-", 2*bmcode-1, "-01")),
         start_date = ym(paste(year, "-", bmcode * 2 - 1)),
         end_date = start_date + months(2) - days(1)) %>%
  filter(year < 2024)



fill_in_missing_denoms <- function(dat) {
    pop_index_2022 <- which.max(dat$year == 2022)
    pop_index_2021 <- which.max(dat$year == 2021)
    dat %>% mutate_at(vars(contains("pop")), ~ ifelse(is.na(.), .[pop_index_2022]^2 / .[pop_index_2021], .))
}

## Hacky imputation
dat <- dat %>%
    group_by(state) %>%
    group_modify(~ fill_in_missing_denoms(.)) %>%
    ungroup()

# compute birth rate per 100 women per year (multiply by 6 for bi months)
dat <- dat %>%
  mutate(birth_rate_total = births_total / pop_total * 1000 * 6,
         log_birth_rate_total = log(birth_rate_total))

# add in the treatment time explicitly
dat %>%
  inner_join(
    dat %>%
  group_by(state) %>%
  summarise(first_trt = min(year_bm[exposed_births == 1])) %>%
  ungroup() %>%
  mutate(first_trt = ifelse(is.finite(first_trt), first_trt, 0))
  ) %>%
  left_join(fips_codes %>% distinct(state_name, state_code), by = c("state" = "state_name")) %>%
  mutate(state_code = as.numeric(state_code)) -> dat

panelview(dat, birth_rate_total ~ exposed_births, index = c("state", "year_bm"))

```





# Full topline estimates (log outcome)
```{r topline_estimates_log, cache = TRUE}

# partially pooled multisynth with a fixed effect
msyn_fixedeff_log <- augsynth(log_birth_rate_total ~ exposed_births, state, year_bm,
                          dat, fixedeff = T, n_leads = 11)

# CS DiD
did_log <- aggte(att_gt("log_birth_rate_total", "year_bm", "state_code", "first_trt",
               data = dat %>% mutate(year_bm = year_bm * 6, first_trt = first_trt * 6),
               base_period = "universal"),
               type = "dynamic")

# fit the factor model explicitly with gsynth
gsyn_log <- gsynth(log_birth_rate_total ~ exposed_births, dat, index = c("state", "year_bm"),
               se = TRUE, inference = "parametric")

# extract results for each estimator
combined_res_log <- bind_rows(
  summary(msyn_fixedeff_log)$att %>% mutate(method = "Multisynth"),
  data.frame(gsyn_log$est.att) %>% rename(Estimate=ATT, Std.Error = S.E.,
                          lower_bound = CI.lower, upper_bound = CI.upper) %>%
    mutate(method = "Factor Model", Time = as.numeric(rownames(.)) - 1,
           Level = "Average"),
  data.frame(Time = did_log$egt, Estimate = did_log$att.egt,
             lower_bound = did_log$att.egt - 2 *  did_log$se.egt,
             upper_bound = did_log$att.egt + 2 * did_log$se.egt) %>%
    mutate(method = "DiD", Level = "Average")
)
```



# Alternative estimators combined with main estimates gap plot

```{r combined_gap_plot}

mtgp_res <- read_csv("event_time_results.csv") %>%
  rename(Time = event_time) %>%
  mutate(Estimate = log(births) - log(ypred_mean),
         lower_bound = log(births) - log(ypred_upper),
         upper_bound = log(births) - log(ypred_lower),
         Level = "Average",
         method = "Primary Estimates",
         Time = Time) %>%
  select(Time, Estimate, lower_bound, upper_bound, Level, method)

combined_res_log %>%
  bind_rows(mtgp_res) %>%
  filter(method %in% c("Multisynth", "DiD", "Factor Model", "Primary Estimates"),
         Level == "Average",
         ) %>%
  mutate(group = case_when(Time < 0 ~ "pre",
                           Time < 7 ~ "post",
                           TRUE ~ "TX only"),
         Time = Time * 2,
         method = relevel(as.factor(method), ref = "Primary Estimates")) %>%
  ggplot(aes(x = Time, y = Estimate, color = method, group = interaction(group, method))) +
  annotate("rect", xmin = 13, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "grey50", alpha = 0.2) +
  geom_ribbon(aes(ymax = upper_bound, ymin =  lower_bound), alpha = 0.25,
              data = . %>% filter(method == "Primary Estimates"), color = NA) +
    # geom_line(data = . %>% filter(method == "MTGP"), color = "black") +
  # geom_line(data = . %>% filter(method != "MTGP")) +
  geom_line() +
  geom_point() +
  annotate("text", x = 17, y = -0.04, label = "TX only") +
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = -1, lty = 3) +
  geom_vline(xintercept = 13, lty = 3) +
  xlab("Months before/after earliest period with exposed births") +
  ylab("Estimated impact on log births per 1000 women per year") +
  # scale_color_brewer("", type = "qual", palette = "Set1") +
  scale_color_manual("", values = c("black", "#1b9e77", "#d95f02", "#7570b3")) +
  theme_bw() +
  theme(legend.position = "bottom")

```